version: '3.9'

services:
  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: ""
    ports:
      - 8000:8000
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    networks:
      - app

  frontend:
    image: node
    tty: true
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/home/node/app
    working_dir: /home/node/app
    command: sh -c 'npm install && npm run dev'
    networks:
      - app

  db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    networks:
      - app

networks:
  app:
    driver: bridge
