services:
  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: ""
    ports:
      - 8000:80
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    networks:
      - app

  frontend:
    image: node
    tty: true
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/home/node/app
    working_dir: /home/node/app
    command: sh -c 'npm install && npm run dev'
    networks:
      - app

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOSTS=%
      - MYSQL_DATABASE=laravel
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    networks:
      - app

networks:
  app:
    driver: bridge
